/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.abastecendo.informacoes;

import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author Aluno TDS
 */
public class LogInUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AbastecendoForm
     */
    public LogInUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterJB = new javax.swing.JButton();
        passwordJTF = new javax.swing.JTextField();
        emailOrPhoneJTF = new javax.swing.JTextField();
        registerJB = new javax.swing.JButton();
        emailOrPhoneJL = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        rememberButton = new javax.swing.JCheckBox();
        accessJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterJB.setText("Enter");
        enterJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterJBActionPerformed(evt);
            }
        });

        passwordJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJTFActionPerformed(evt);
            }
        });

        registerJB.setText("Register");
        registerJB.setToolTipText("");
        registerJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJBActionPerformed(evt);
            }
        });

        emailOrPhoneJL.setText("Email or Phone");

        passwordLabel.setText("Password");

        rememberButton.setText("Remember");
        rememberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberButtonActionPerformed(evt);
            }
        });

        accessJL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accessJL.setText("Access");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailOrPhoneJL)
                    .addComponent(passwordLabel)
                    .addComponent(rememberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(registerJB))
                        .addComponent(passwordJTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailOrPhoneJTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accessJL)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accessJL)
                .addGap(18, 18, 18)
                .addComponent(emailOrPhoneJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailOrPhoneJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rememberButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterJB)
                    .addComponent(registerJB))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJBActionPerformed
        // TODO add your handling code here:
        RegistrarUsuario cadastro = new RegistrarUsuario(this,true);
        cadastro.setVisible(true);
    }//GEN-LAST:event_registerJBActionPerformed

    private void passwordJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJTFActionPerformed

    private void rememberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberButtonActionPerformed

    private void enterJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterJBActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_enterJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    //javax.swing.UIManager.setLookAndFeel(new FlatLightLaf()); // Light
    javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf()); // Dark
    //javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf()); // Intellij
    //javax.swing.UIManager.setLookAndFeel(new FlatDarculaLaf()); // Dracula
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(LogInUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessJL;
    private javax.swing.JLabel emailOrPhoneJL;
    private javax.swing.JTextField emailOrPhoneJTF;
    private javax.swing.JButton enterJB;
    private javax.swing.JTextField passwordJTF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerJB;
    private javax.swing.JCheckBox rememberButton;
    // End of variables declaration//GEN-END:variables
}
