/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.abastecendo.informacoes;

/**
 *
 * @author Vaio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        direcaoJTF = new javax.swing.JTextField();
        informacoesDoVeiculo = new javax.swing.JButton();
        verMaisJL = new javax.swing.JLabel();
        playlistJL = new javax.swing.JLabel();
        cadastrarPostoJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        direcaoJTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direcaoJTF.setText("Para onde?");
        direcaoJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direcaoJTFActionPerformed(evt);
            }
        });

        informacoesDoVeiculo.setText("Informações do Veículo");
        informacoesDoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesDoVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(direcaoJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(informacoesDoVeiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(informacoesDoVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(direcaoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        verMaisJL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        verMaisJL.setForeground(new java.awt.Color(255, 255, 0));
        verMaisJL.setText("Ver mais");
        verMaisJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMaisJLMouseClicked(evt);
            }
        });

        playlistJL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        playlistJL.setForeground(new java.awt.Color(255, 255, 51));
        playlistJL.setText("Playlist");
        playlistJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlistJLMouseClicked(evt);
            }
        });

        cadastrarPostoJL.setForeground(new java.awt.Color(255, 255, 0));
        cadastrarPostoJL.setText("Cadastrar Posto");
        cadastrarPostoJL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarPostoJLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verMaisJL)
                .addGap(90, 90, 90)
                .addComponent(cadastrarPostoJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playlistJL)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verMaisJL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playlistJL)
                    .addComponent(cadastrarPostoJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void direcaoJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direcaoJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direcaoJTFActionPerformed

    private void verMaisJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMaisJLMouseClicked
        VerMais ver = new VerMais();
        ver.setVisible(true);
    }//GEN-LAST:event_verMaisJLMouseClicked

    private void playlistJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlistJLMouseClicked
        Playlist playList = new Playlist(this,  true);
        playList.setVisible(true);
    }//GEN-LAST:event_playlistJLMouseClicked

    private void informacoesDoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesDoVeiculoActionPerformed
        InformacoesDoVeiculo informacoes = new InformacoesDoVeiculo();
        informacoes.setVisible(true);
    }//GEN-LAST:event_informacoesDoVeiculoActionPerformed

    private void cadastrarPostoJLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarPostoJLMouseClicked
        CadastrarPosto cadastrar = new CadastrarPosto(this, true);
        cadastrar.setVisible(true);
    }//GEN-LAST:event_cadastrarPostoJLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrarPostoJL;
    private javax.swing.JTextField direcaoJTF;
    private javax.swing.JButton informacoesDoVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playlistJL;
    private javax.swing.JLabel verMaisJL;
    // End of variables declaration//GEN-END:variables
}
